-- Rooms
create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now()
);

-- Messages (optional persisted history)
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid references public.rooms(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  content text not null,
  created_at timestamptz default now()
);

-- RLS
alter table public.rooms enable row level security;
alter table public.messages enable row level security;

create policy "rooms are readable by all" on public.rooms for select using (true);
create policy "insert rooms if authed" on public.rooms for insert with check (auth.uid() = created_by);

create policy "messages readable by all" on public.messages for select using (true);
create policy "insert messages if authed" on public.messages for insert with check (auth.uid() = user_id);


