/**
 * Project-root env shim
 * Keeps old imports like '../../env' working while canonical env moved to src/env.ts
 * Auto-generated by diagnostic script — safe to keep or remove after you update imports.
 */
try {
  // prefer canonical src/env if available
  // eslint-disable-next-line @typescript-eslint/no-var-requires, global-require
  const mod = require('./src/env');
  // CommonJS consumers
  module.exports = mod;
  // ES exports
  exports.default = mod.default || mod;
  Object.keys(mod).forEach(k => { if (k !== 'default') exports[k] = mod[k]; });
} catch (e) {
  // fallback: minimal ENV so app doesn't crash immediately
  // eslint-disable-next-line no-console
  console.warn('[env shim] ./src/env not found. Using fallback values.');
  const FALLBACK = {
    SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL || '',
    SUPABASE_ANON: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || '',
    FUNCTIONS_BASE: process.env.EXPO_PUBLIC_FUNCTIONS_BASE_URL || '',
    HMS_TOKEN_URL: process.env.EXPO_PUBLIC_HMS_TOKEN_URL || '',
    HMS_LISTENER_ROLE: process.env.EXPO_PUBLIC_HMS_LISTENER_ROLE || 'listener',
    HMS_SPEAKER_ROLE: process.env.EXPO_PUBLIC_HMS_SPEAKER_ROLE || 'speaker',
    HMS_MODERATOR_ROLE: process.env.EXPO_PUBLIC_HMS_MODERATOR_ROLE || 'moderator',
  };
  module.exports = FALLBACK;
  exports.default = FALLBACK;
  Object.keys(FALLBACK).forEach(k => { exports[k] = FALLBACK[k]; });
}


